# Generated by Django 4.0.5 on 2022-06-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('survey_number', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=50)),
                ('farm_area', models.CharField(max_length=20)),
            ],
        ),
    ]
