# Generated by Django 4.0.5 on 2022-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landrecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrec',
            name='framer_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
